// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR_bEEB2GqlnZqMd1Sg0wrSE5bFaCRmpQ',
    appId: '1:727083765627:web:ed651a8f055f7be71177de',
    messagingSenderId: '727083765627',
    projectId: 'fir-example-96ad0',
    authDomain: 'fir-example-96ad0.firebaseapp.com',
    storageBucket: 'fir-example-96ad0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPIAaCO6U17nL_Nk4PSJtGDocCIeVQZCg',
    appId: '1:727083765627:android:47dfc3e62e7627511177de',
    messagingSenderId: '727083765627',
    projectId: 'fir-example-96ad0',
    storageBucket: 'fir-example-96ad0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh_TzgdTrpuum3IhrWjp_iSq-V7yS3ZPs',
    appId: '1:727083765627:ios:c0c4a9cc1fc60c431177de',
    messagingSenderId: '727083765627',
    projectId: 'fir-example-96ad0',
    storageBucket: 'fir-example-96ad0.appspot.com',
    androidClientId: '727083765627-itpgpfej6bc2ic85h5jpp2ikj1qbhqbn.apps.googleusercontent.com',
    iosClientId: '727083765627-o4jnqu5jjauh1l51rp8jif5bg34firm1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh_TzgdTrpuum3IhrWjp_iSq-V7yS3ZPs',
    appId: '1:727083765627:ios:05fb01587ed86e731177de',
    messagingSenderId: '727083765627',
    projectId: 'fir-example-96ad0',
    storageBucket: 'fir-example-96ad0.appspot.com',
    androidClientId: '727083765627-itpgpfej6bc2ic85h5jpp2ikj1qbhqbn.apps.googleusercontent.com',
    iosClientId: '727083765627-fnm0592nuh0dis8aob2v2kf51ti2km86.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
